<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-PupaMVCF.ExampleTest-b94247b3-8079-43a7-8d20-ecfb818247fd</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>PupaMVCF.ExampleProcess</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <FilesProject Include="$(ProjectDir)/environment/**/*"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\PupaMVCF.Framework\PupaMVCF.Framework.csproj"/>
    </ItemGroup>
    <Target Name="BuildEnv" AfterTargets="Build">
        <Copy SourceFiles="@(FilesProject)" DestinationFolder="$(TargetDir)/%(RecursiveDir)"/>
    </Target>
    <Target Name="PublishEnv" AfterTargets="Publish">
        <Copy SourceFiles="@(FilesProject)" DestinationFolder="$(PublishDir)/%(RecursiveDir)"/>
    </Target>
</Project>
