name: Deploy PupaMVCF Template nuget pacakge 

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_FRAMEWORK_PATH: 'src/PupaMVCF.Framework/PupaMVCF.Framework.csproj'
  PROJECT_TESTS_PATH: 'src/PupaMVCF.Tests/PupaMVCF.Tests.csproj'
  PROJECT_FRAMEWORK_TEMPLATE_PATH: 'src/PupaMVCF.Template/PupaMVCF.Template.csproj'
  NUGET_SOURCE_URI: "https://api.nuget.org/v3/index.json"
  GITHUB_USERNAME: "Artpupser"
  OUTPUT_NUPKG_FILE: ${{ github.workspace }}/output/*.nupkg
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/output

permissions:
  contents: read
  packages: write
  
jobs:
  test:
    name: "Testing PupaMVCF.Framework"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: Restore csharp projects
        run: |
          dotnet restore ${{ env.PROJECT_FRAMEWORK_PATH }}
          dotnet restore ${{ env.PROJECT_TESTS_PATH }}

      - name: Build csharp projects
        run: |
          dotnet build ${{ env.PROJECT_FRAMEWORK_PATH }} --configuration Release --no-restore
          dotnet build ${{ env.PROJECT_TESTS_PATH }} --configuration Release --no-restore

      - name: Run xUnit tests
        run: |
          dotnet test ${{ env.PROJECT_TESTS_PATH }} \
          --no-build \
          --configuration Release \
          --verbosity normal \
          --logger "trx;LogFileName=test-report.trx"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/*.trx'
  deploy-template:
    name: "Deploy PupaMVCF.Template"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore template project
        run: dotnet restore ${{ env.PROJECT_FRAMEWORK_TEMPLATE_PATH }}

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Pack template
        run: |
          dotnet pack ${{ env.PROJECT_FRAMEWORK_TEMPLATE_PATH }} \
          --no-restore \
          --configuration Release \
          --include-symbols \
          -p:PackageVersion=${{ env.VERSION }} \
          --output ${{ env.PACKAGE_OUTPUT_DIR }}

      - name: Push template to NuGet
        run: |
          dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg" \
          --skip-duplicate \
          -k ${{ secrets.NUGET_AUTH_TOKEN_TEMPLATE }} \
          -s ${{ env.NUGET_SOURCE_URI }}